using System.Text;
using Dreamy.Audio;

namespace Dreamy.Audio.Editor
{
    public static class AudioKeyGenerator
    {
        public static string Generate(DreamyAudioCatalog catalog)
        {
            var ns = string.IsNullOrWhiteSpace(catalog.GeneratedNamespace) ? "Dreamy.Audio.Generated" : catalog.GeneratedNamespace;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Dreamy Audio. Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using Dreamy.Audio;");
            sb.AppendLine();
            sb.Append("namespace ").AppendLine(ns);
            sb.AppendLine("{");
            sb.AppendLine("    public static class AudioKeys");
            sb.AppendLine("    {");

            for (var i = 0; i < catalog.Events.Count; i++)
            {
                var audioEvent = catalog.Events[i];
                if (audioEvent == null || !AudioKey.IsValidPart(audioEvent.Key))
                {
                    continue;
                }

                sb.Append("        public static readonly AudioKey ")
                    .Append(ToIdentifier(audioEvent.Key))
                    .Append(" = new AudioKey(\"")
                    .Append(Escape(catalog.CatalogId))
                    .Append("\", \"")
                    .Append(Escape(audioEvent.Key))
                    .AppendLine("\");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string Generate(AudioLibrary library)
        {
            var ns = string.IsNullOrWhiteSpace(library.GeneratedNamespace) ? "Dreamy.Audio.Generated" : library.GeneratedNamespace;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Dreamy Audio. Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using Dreamy.Audio;");
            sb.AppendLine();
            sb.Append("namespace ").AppendLine(ns);
            sb.AppendLine("{");
            AppendEnum(sb, library.SoundEnumName, library.Sounds);
            sb.AppendLine();
            AppendEnum(sb, library.MusicEnumName, library.Music);
            sb.AppendLine();
            sb.AppendLine("    public static class AudioLibraryKeys");
            sb.AppendLine("    {");
            AppendKeyClass(sb, "Sounds", library.LibraryId, library.Sounds);
            AppendKeyClass(sb, "Music", library.LibraryId, library.Music);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string ToIdentifier(string key)
        {
            var sb = new StringBuilder();
            var capitalizeNext = true;
            for (var i = 0; i < key.Length; i++)
            {
                var c = key[i];
                if (!char.IsLetterOrDigit(c))
                {
                    capitalizeNext = true;
                    continue;
                }

                if (sb.Length == 0 && char.IsDigit(c))
                {
                    sb.Append('_');
                }

                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }

            return sb.Length == 0 ? "InvalidAudioKey" : sb.ToString();
        }

        private static string Escape(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static void AppendEnum<T>(StringBuilder sb, string enumName, System.Collections.Generic.IReadOnlyList<T> files) where T : AudioFileObject
        {
            sb.Append("    public enum ").AppendLine(ToIdentifier(enumName));
            sb.AppendLine("    {");
            for (var i = 0; i < files.Count; i++)
            {
                var file = files[i];
                if (file == null || !AudioKey.IsValidPart(file.Key))
                {
                    continue;
                }

                sb.Append("        ").Append(ToIdentifier(file.Key)).AppendLine(",");
            }

            sb.AppendLine("    }");
        }

        private static void AppendKeyClass<T>(StringBuilder sb, string className, string libraryId, System.Collections.Generic.IReadOnlyList<T> files) where T : AudioFileObject
        {
            sb.Append("        public static class ").AppendLine(className);
            sb.AppendLine("        {");
            for (var i = 0; i < files.Count; i++)
            {
                var file = files[i];
                if (file == null || !AudioKey.IsValidPart(file.Key))
                {
                    continue;
                }

                sb.Append("            public static readonly AudioKey ")
                    .Append(ToIdentifier(file.Key))
                    .Append(" = new AudioKey(\"")
                    .Append(Escape(libraryId))
                    .Append("\", \"")
                    .Append(Escape(file.Key))
                    .AppendLine("\");");
            }

            sb.AppendLine("        }");
        }
    }
}
