using System;
using System.Collections.Generic;
using System.Text;
using Dreamy.Audio;

namespace Dreamy.Audio.Editor
{
    public static class AudioKeyGenerator
    {
        public static bool TryValidateLibrary(AudioLibrary library, out string error)
        {
            if (library == null)
            {
                error = "Audio Library is null.";
                return false;
            }

            var ids = new HashSet<string>();
            foreach (var file in library.EnumerateFiles())
            {
                if (file == null) continue;
                var id = library.LibraryId + "/" + file.Key;
                if (!ids.Add(id))
                {
                    error = "Duplicate runtime ID: " + id;
                    return false;
                }
            }

            error = null;
            return true;
        }

        public static string Generate(AudioLibrary library)
        {
            if (!TryValidateLibrary(library, out var error)) throw new InvalidOperationException(error);
            var ns = "Dreamy.Audio.Generated";
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Dreamy Audio. Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.Append("namespace ").AppendLine(ns);
            sb.AppendLine("{");
            sb.AppendLine("    public static class AudioLibraryIds");
            sb.AppendLine("    {");
            AppendKeyClass(sb, "Sounds", library.LibraryId, library.Sounds);
            AppendKeyClass(sb, "Music", library.LibraryId, library.Music);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string ToIdentifier(string key)
        {
            var sb = new StringBuilder();
            var capitalizeNext = true;
            for (var i = 0; i < key.Length; i++)
            {
                var c = key[i];
                if (!char.IsLetterOrDigit(c))
                {
                    capitalizeNext = true;
                    continue;
                }

                if (sb.Length == 0 && char.IsDigit(c))
                {
                    sb.Append('_');
                }

                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }

            return sb.Length == 0 ? "InvalidAudioKey" : sb.ToString();
        }

        private static string Escape(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static void AppendKeyClass<T>(StringBuilder sb, string className, string libraryId, System.Collections.Generic.IReadOnlyList<T> files) where T : AudioFileObject
        {
            sb.Append("        public static class ").AppendLine(className);
            sb.AppendLine("        {");
            for (var i = 0; i < files.Count; i++)
            {
                var file = files[i];
                if (file == null || !AudioKey.IsValidPart(file.Key))
                {
                    continue;
                }

                sb.Append("            public const string ")
                    .Append(ToIdentifier(file.Key))
                    .Append(" = \"")
                    .Append(Escape(libraryId))
                    .Append("/")
                    .Append(Escape(file.Key))
                    .AppendLine("\";");
            }

            sb.AppendLine("        }");
        }
    }
}
