using System.Text;
using Dreamy.Audio;

namespace Dreamy.Audio.Editor
{
    public static class AudioKeyGenerator
    {
        public static string Generate(DreamyAudioCatalog catalog)
        {
            var ns = string.IsNullOrWhiteSpace(catalog.GeneratedNamespace) ? "Dreamy.Audio.Generated" : catalog.GeneratedNamespace;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Dreamy Audio. Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using Dreamy.Audio;");
            sb.AppendLine();
            sb.Append("namespace ").AppendLine(ns);
            sb.AppendLine("{");
            sb.AppendLine("    public static class AudioKeys");
            sb.AppendLine("    {");

            for (var i = 0; i < catalog.Events.Count; i++)
            {
                var audioEvent = catalog.Events[i];
                if (audioEvent == null || !AudioKey.IsValidPart(audioEvent.Key))
                {
                    continue;
                }

                sb.Append("        public static readonly AudioKey ")
                    .Append(ToIdentifier(audioEvent.Key))
                    .Append(" = new AudioKey(\"")
                    .Append(Escape(catalog.CatalogId))
                    .Append("\", \"")
                    .Append(Escape(audioEvent.Key))
                    .AppendLine("\");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string ToIdentifier(string key)
        {
            var sb = new StringBuilder();
            var capitalizeNext = true;
            for (var i = 0; i < key.Length; i++)
            {
                var c = key[i];
                if (!char.IsLetterOrDigit(c))
                {
                    capitalizeNext = true;
                    continue;
                }

                if (sb.Length == 0 && char.IsDigit(c))
                {
                    sb.Append('_');
                }

                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }

            return sb.Length == 0 ? "InvalidAudioKey" : sb.ToString();
        }

        private static string Escape(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
